title: "GURJAOLAB"
description: "GURJAOLAB"
url: ""
baseurl: ""
permalink: pretty

collections_dir: Pages
collections:
  pages:
    output: true
    permalink: /:name/

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - README.md
