title: "GURJAOLAB"
url: "https://joseph-gad-code.github.io"
baseurl: "/Gurjao-Lab-Website"
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name/

collections_dir: pages

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - README.md
