title: "GURJAOLAB"
description: "GURJAOLAB website"
url: "https://joseph-gad-code.github.io"
baseurl: "/Gurjao-Lab-Website"

permalink: pretty

collections_dir: pages
collections:
  pages:
    output: true
    permalink: /:name/

sass:
  style: compressed

defaults:
  - scope: { path: "" }
    values:
      layout: default

exclude:
  - README.md
