title: "GURJAOLAB"

# Project site (no custom domain):
url: "https://joseph-gad-code.github.io"
baseurl: "/Gurjao-Lab-Website"

permalink: pretty

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - README.md
  
