site_title: "GURJAOLAB"
favicon_path: "/assets/images/favicon-32x32.png"

container_max_width: 1120px
page_padding_x: 16px

font_family_base: "'Nunito', system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif"
font_weight_normal: 400
font_weight_bold: 700

text_color: "#111"
link_color: "#0D5295"
brand_color: "#0D5295"

nav:
  - { label: "Home",         url: "/" }
  - { label: "Research",     url: "/research/" }
  - { label: "Publications", url: "/publications/" }
  - { label: "People",       url: "/people/" }
  - { label: "Contact",      url: "/contact/" }
