name: Sync Google Scholar to publications.yml

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * 1"   # weekly

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install minimal deps
        run: |
          npm init -y
          npm i cheerio js-yaml

      - name: Run sync
        env:
          SCHOLAR_USER_ID: m3rLfS4AAAAJ
        run: node scripts/sync-scholar.js

      - name: Commit updates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add _data/publications.yml
            git commit -m "Sync publications from Scholar"
            git push
          fi
