name: Sync Google Scholar -> publications.yml

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # every Monday 06:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm init -y
          npm i js-yaml google-search-results-nodejs

      - name: Run sync (SerpAPI)
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SCHOLAR_AUTHOR_ID: m3rLfS4AAAAJ
        run: node scripts/sync-scholar-serpapi.js

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git add _data/publications.yml
            git commit -m "Sync publications from Google Scholar (SerpAPI)"
            git push
          else
            echo "No changes."
          fi
