name: Sync Google Scholar -> publications.yml

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # every Monday 06:00 UTC (adjust as you like)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Fetch Scholar & write YAML
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: npm run sync:scholar

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add _data/publications.yml
            git commit -m "Update publications.yml from Google Scholar"
            git push
          else
            echo "No changes."
          fi
