name: Update Publications

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'     # runs every Monday at 08:00 UTC

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run update script
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          python update_publications.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add _data/publications.yml
            git commit -m "Auto-update publications [skip ci]"
            git push
          else
            echo "No changes in publications.yml"
          fi
